### ISSUE TITLE
arm.content module not installing via pip

### ISSUE THREAD

**Issue by ivvvve** [armstrong/armstrong#101]
pip install reaches a snag --

```
 Collecting armstrong.core.arm-content<1.1,>=1.3.1 (from armstrong)
 Could not find a version that satisfies the requirement armstrong.core.arm-content
```

Could this be a misplaced hypen?

**Comment by joncotton** [comment]
The hyphen is okay. Are you failing on a dependency? My installation attempt fails at:

```
Downloading/unpacking django-reversion==1.4 (from armstrong.core.arm-content<1.1,>=1.3.1->armstrong)
  Could not find a version that satisfies the requirement django-reversion==1.4 (from armstrong.core.arm-content<1.1,>=1.3.1->armstrong) (from versions: 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.7.1, 1.7, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5)
  Some externally hosted files were ignored (use --allow-external to allow).
Cleaning up...
No distributions matching the version for django-reversion==1.4 (from armstrong.core.arm-content<1.1,>=1.3.1->armstrong)
```

That's because django-reversion 1.4 is ancient and no longer available on PyPi. You can install it from our github "mirror" with this command:
`pip install https://github.com/armstrong/pypi.armstrongcms.org/raw/gh-pages/files/django-reversion-1.4.tar.gz`
Then it dies on PIL; to compensate: `pip install https://github.com/armstrong/pypi.armstrongcms.org/raw/gh-pages/files/PIL-1.1.7.tar.gz`

All the packages Armstrong needs are there on our Github (make sure to pip install with the `raw` link). But there's a larger issue and that is the `armstrong` **bundle is unmaintained**. The last _full_ bundle release was April 2, 2012. You should use a newer Django Reversion, Pillow not PIL, current release of Django, etc. There is still life to Armstrong, which is awesomely modular, and its **components are still alive**. Anything recently updated (see [parent Github page](https://github.com/armstrong)) is worth considering. You'll also recognize maintained Armstrong components because they have badges (for PyPi, test coverage, etc).

**Comment by ivvvve** [comment]
Thanks for your comprehensive reply! Will have a go at the above.

**Comment by joncotton** [comment]
I'll close this. Let me know if I can help with any of the individual components.
