### ISSUE TITLE
add disqus commenting to project templates

### ISSUE THREAD

**Issue by tinio** [armstrong/armstrong#22]

**Comment by tswicegood** [comment]
This belongs in the `standard` project in `armstrong.cli`.  The `demo` project template should probably also have comments added, but that one would ideally have some faux-comments back-filled in.  Probably worth talking with the Disqus guys to see what the best way about doing that is.

**Comment by tswicegood** [comment]
Another thing to do here is put the configuration inside a `settings.extras.disqus` module and comment it out inside the main `settings.defaults` along with comments explaining how to turn it on/off and how when you'd want to put that information inside `settings.development` and `settings.production` instead of site-wide.

**Comment by tswicegood** [comment]
Closing a this already opened in #7.  Forgot I had added.
