### ISSUE TITLE
Revisit test runner for Armstrong

### ISSUE THREAD

**Issue by tswicegood** [armstrong/armstrong#48]
Currently the bulk of the time spent running tests in a CI environment is spent installing stuff.  Because we use Fabric we end up having to install a bunch of crypto stuff which requires real compiles.

The choice to use Fabric as the test runner was done before we had the `armstrong.cli` project.  At this point it's probably worth adding a command to run tests through that and removing Fabric as a dependency.

**Comment by joncotton** [comment]
I agree that most of the time running tests is spent installing stuff and we can do better. My thoughts boil down to an improved ArmDev (2.0) that uses Invoke and stick with Django's test runner.
- I think ArmCLI isn't the way particularly because it's being deprecated. See #67 
- Django has a fine test runner, let's keep using it. (Fabric isn't actually the runner, just the means to invoke it.)
- Invoke is the stripped-down Fabric without the SSH/crypto (thanks @crccheck for this)
- ArmDev is in the progress of significant improvement see armstrong/armstrong.dev#12

**Comment by crccheck** [comment]
One thing to note is Django changed their test discovery (for the better) in 1.6 [details](https://docs.djangoproject.com/en/dev/releases/1.6/#discovery-of-tests-in-any-test-module). "This change is backwards-incompatible; see the backwards-incompatibility notes." I know you can organize tests so they run in all recent versions of Django, but I don't remember what I had to do.

@tswicegood What's your experience with using detox vs tox and TravisCI?

**Comment by joncotton** [comment]
This is how I've punted on that issue, just to use the old test runner for now. joncotton/armstrong.core.arm_layout@80a3efa11f8f2913d3ce90668b4e9c7eaa5ada9c

**Comment by joncotton** [comment]
I've been playing with the Django 1.6 test runner (which is really unittest's discover runner) and I like it. It means potentially more typing when specifying a subset of tests because now you need the entire path instead of the `app_name.test` pseudo path. But the benefits are greater.

The new runner doesn't run tests for everything in INSTALLED_APPS, uses flexible pattern matching to find test files, and starts in the current working directory. This means a) we can remove the code we have to avoid testing everything in INSTALLED_APPS and b) it's easy to move the `tests/` directory, which means it's easy to **stop shipping tests**. This is essentially exactly what @crccheck said in this longer [discussion](https://github.com/armstrong/armstrong.dev/pull/12#issuecomment-16272555).

Bonus, if we move the `tests/` directory into the root of the project, specifying the full path for the runner is easy, e.g. `manage.py test tests.testcase1 tests.testcase2 ...`

A PR for ArmDev 2.0 is near.

**Comment by joncotton** [comment]
ArmDev 2.0 is released and it addresses this. Closing.
