### ISSUE TITLE
Add an inline tag

### ISSUE THREAD

**Issue by epicserve** [armstrong/armstrong#58]
It would be nice if there was an inline tag that could be used to add inline elements inside any content TextArea field. Ellington and Django-basic-apps both have this functionality. Also, when importing [NTIF](http://en.wikipedia.org/wiki/National_Imagery_Transmission_Format) news articles it makes sense to import the inlines in a NTIF document as inlines in the CMS in order to maintain the inline elements placement. Have a look at [Django-basic-apps](https://github.com/nathanborror/django-basic-apps/blob/master/README.rst) for documentation and ideas on how Nathan implemented inlines.

**Comment by tswicegood** [comment]
We've had this discussion internally here at the Tribune a lot.  Right now the thinking is that we don't want to introduce a new XML tag to what is HTML.  What happens if we move to Markdown or someone wants to use Textile?  Are we going to start extending those mark-up languages too?

Beyond the custom markup issue, there are couple of bigger problems. problem.  1) Now display elements are tied up in content.  The fact that an Image or Tweet or WeatherReport is inline in the body of an article is potentially true for only one display form.  2) Where is the relationship defined?  What if you want to pull those "inline" images from the web page and make a photo gallery that's associated with the article if you're on a mobile app?

These considerations have lead us to push this further down the stack.  Items you want to display "inline" would be related via [armstrong.apps.related_content](http://github.com/armstrong/armstrong.apps.related_content/), then [armstrong.core.arm_layout](http://github.com/armstrong/armstrong.core.arm_layout/) would be responsible for rendering that model.  This is what I was referring to in #55 about the future plans for arm_layout.

The idea still very much in the nacent stage, both from a technical stand-point and what the UI will look like.  Both of those are pretty important to get right (or close to right) on something like this, though.  Technically, we don't want to handicap an Armstrong app by undercutting URL routing and custom views.  From a user's perspective, we also don't want force extra steps for the default case while still offering the flexibility of changing things up.

In the meantime, there is no plan to implement inlines (for the reasons stated above), so I'm closing this ticket.

**Comment by epicserve** [comment]
Without being able to control where an inline element like a photo is inserted, could be the missing feature that prevents our Newspaper from going with Armstrong. This is a feature we have now with Ellington and every other CMS we've looked at provides this functionally.

**Comment by tswicegood** [comment]
You will be able to control where the related content is displayed, just at a different layer.  It's also something you're welcome to contribute as part of the Armstrong community, but it will need to be maintained outside of the official `armstrong` namespace for the reasons mentioned above.

**Comment by epicserve** [comment]
So in order to position an inline element where I want it in the body of the text, I would do what exactly? How would that work  exactly in the Admin UI?

**Comment by epicserve** [comment]
> What happens if we move to Markdown or someone wants to use Textile? Are we going to start extending those mark-up languages too?

I use Markdown and HTML both in my own CMS and my inline parser templatetag has never ran into any issues so I'm not sure I understand this argument.

**Comment by epicserve** [comment]
>  1) Now display elements are tied up in content. The fact that an Image or Tweet or WeatherReport is inline in the body of an article is potentially true for only one display form.

In my own CMS, I handle this with a templatetag that removes the inlines I don't want.

> 2) Where is the relationship defined? What if you want to pull those "inline" images from the web page and make a photo gallery that's associated with the article if you're on a mobile app?

I wouldn't put those things in the admin as inlines. I would add them as related content.

**Comment by mediacobbler** [comment]
hey epicserve, im working in ellington and need to make a loop that displays all of the inline images in a particular category. can you help me?
