### ISSUE TITLE
Create a media app

### ISSUE THREAD

**Issue by epicserve** [armstrong/armstrong#59]
It seems like the CMS would be more organized if all media type models (i.e. armstrong.apps.images, armstrong.apps.embedded_video) where under one app called Media. Here is a screenshot of how that looks in another Django CMS.

![Screenshot](http://f.cl.ly/items/1e0C2S010U3A3K3n2026/Screen%20Shot%202012-04-10%20at%202.18.33%20PM.png)

**Comment by tswicegood** [comment]
This is something that's planned, but through a slightly different route.  Rather than merging the apps at the app level, they'll be merged into groups in the admin via [admin-tools](http://django-admin-tools.readthedocs.org/en/latest/).  This keeps all of the applications independent, while providing a logical grouping at the interface level.

**Comment by joncotton** [comment]
Closing as no longer relevant. AppsImages is a super weak point and really really needs replacing (Bay Citizen has draft code but who knows if it'll ever see the light). AppsEmbeddedVideo is unmaintained; for things like this [armstrong.apps.embeds](https://github.com/armstrong/armstrong.apps.embeds) is a much better solution.

I do agree with Travis's approach of independent apps and interface grouping. For the record.
