### ISSUE TITLE
Pinning Django 1.4.4? 

### ISSUE THREAD

**Issue by Jbonnett** [armstrong/armstrong#88]
https://www.djangoproject.com/weblog/2013/feb/20/updated-releases-issued/

I would argue that pinning the minor version is a waste of time. If the django team says 1.4.4 and 1.4.5 are compatible, are we really so sure that we know better?

**Comment by tswicegood** [comment]
Until Django 1.5, yes.  Starting in Django 1.5, no new features are added to tertiary point releases, but in 1.4.x they were.  There's code somewhere in Armstrong that broke in 1.4.4 or 1.4.5 (I'd have to go dig it up) because of a new feature that was added.  The idea with pinning to a tertiary release was that we'd re-run our code on the new releases as it came out to ensure that it worked, then bump the version requirement.

All that said, once the various Django requirements are removed as part of Armstrong v13.06, this will play less of a roll.

**Comment by Jbonnett** [comment]
works for me.
